### ISSUE TITLE
Possibility for no gaps?

### ISSUE THREAD

**Issue by harrygcoppock** [houseofcommonslibrary/uk-hex-cartograms-noncontiguous#4]
Hi, thank you for this great repo. 

I was wondering if it was possible to remove the 'gaps'? Yeilding a plot which looked something like this?
<img width="452" alt="Screenshot 2021-11-01 at 11 26 35" src="https://user-images.githubusercontent.com/59699137/139664414-47217daf-8d0f-4004-8256-80f7c0326809.png">

**Comment by bakerc-hoc** [comment]
Hi there, thanks for the comment. 

I think it would be possible to generate a contiguous version like the above but ultimately it would be a totally new project rather than an evolution of this one. I consider the non-contiguous feature of this project to be pretty fundamental.

But unlike these templates, you might be able to generate a contiguous version algorithmically, and folks have looked at this. Some links that may be of interest:
https://github.com/jbaileyh/geogrid
https://theconversation.com/even-the-most-beautiful-maps-can-be-misleading-126474

**Comment by harrygcoppock** [comment]
Yes, I agree as the whole point of this repo was to add back in geographical clarity. Cheers for the links, I will check them out.
